<a href="https://colab.research.google.com/github/Wduce29/Resume-web/blob/main/Copy_of_DTSC610_HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 3: Numpy and Pandas

> Please complete this notebook below by filling in the cells provided. Note you need to save a copy in your own Colab to modify it:
before you start working, **SAVE A COPY (File --> Save a copy in Drive)** in your own Google Drive to modify the notebook.

When you’re done:

1. Select `Run All` from the `Cell` menu to ensure that you have executed all cells.
2. Select `Download .ipynb` from the `File` menu
3. Convert the downloaded ` .ipynb` file to ` .html` file (see instruction at end of this file)
4. Submit that downloaded ` .html` file to Canvas.


Reading:
- [1](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.02-The-Basics-Of-NumPy-Arrays.ipynb)
- [2](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/03.03-Operations-in-Pandas.ipynb)

# Practice: Intro to Pandas

First we need to import the `pandas` package. Let's give it the same special nickname we used before—`pd`.

In [ ]:
import pandas as pd

Now we'll create a `DataFrame`. Modify this cell to save it to a variable called `car_data`.

In [ ]:
car_data = pd.DataFrame({'acceleration': [12.0,11.5,11.0,12.0,10.5,10.0,9.0,8.5,10.0,8.5,10.0,8.0,9.5,10.0,15.0,15.5,15.5,16.0,14.5,20.5],
 'cylinders': [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 6, 6, 6, 4, 4],
 'displacement': [307.0,350.0,318.0,304.0,302.0,429.0,454.0,440.0,455.0,390.0,383.0,340.0,400.0,455.0,113.0,198.0,199.0,200.0,97.0,97.0],
 'horsepower': [130.0,165.0,150.0,150.0,140.0,198.0,220.0,215.0,225.0,190.0,170.0,160.0,150.0,225.0,95.0,95.0,97.0,85.0,88.0,46.0],
 'model_year': [70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70],
 'mpg': [18.0,15.0,18.0,16.0,17.0,15.0,14.0,14.0,14.0,15.0,15.0,14.0,15.0,14.0,24.0,22.0,18.0,21.0,27.0,26.0],
 'name': ['chevrolet chevelle malibu','buick skylark 320','plymouth satellite','amc rebel sst','ford torino','ford galaxie 500','chevrolet impala','plymouth fury iii','pontiac catalina','amc ambassador dpl','dodge challenger se',"plymouth 'cuda 340",'chevrolet monte carlo','buick estate wagon (sw)','toyota corona mark ii','plymouth duster','amc hornet','ford maverick','datsun pl510','volkswagen 1131 deluxe sedan'],
 'origin': ['usa','usa','usa','usa','usa','usa','usa','usa','usa','usa','usa','usa','usa','usa','japan','usa','usa','usa','japan','europe'],
 'weight': [3504,3693,3436,3433,3449,4341,4354,4312,4425,3850,3563,3609,3761,3086,2372,2833,2774,2587,2130,1835]})

Now explore the `car_data` `DataFrame`. View the first few rows:

In [ ]:
# view the first 5 rows
car_data.head()

,acceleration,cylinders,displacement,horsepower,model_year,mpg,name,origin,weight
0,12.0,8,307.0,130.0,70,18.0,chevrolet chevelle malibu,usa,3504
1,11.5,8,350.0,165.0,70,15.0,buick skylark 320,usa,3693
2,11.0,8,318.0,150.0,70,18.0,plymouth satellite,usa,3436
3,12.0,8,304.0,150.0,70,16.0,amc rebel sst,usa,3433
4,10.5,8,302.0,140.0,70,17.0,ford torino,usa,3449

In [ ]:
# view the first 10 rows
car_data.head(10)

,acceleration,cylinders,displacement,horsepower,model_year,mpg,name,origin,weight
0,12.0,8,307.0,130.0,70,18.0,chevrolet chevelle malibu,usa,3504
1,11.5,8,350.0,165.0,70,15.0,buick skylark 320,usa,3693
2,11.0,8,318.0,150.0,70,18.0,plymouth satellite,usa,3436
3,12.0,8,304.0,150.0,70,16.0,amc rebel sst,usa,3433
4,10.5,8,302.0,140.0,70,17.0,ford torino,usa,3449
5,10.0,8,429.0,198.0,70,15.0,ford galaxie 500,usa,4341
6,9.0,8,454.0,220.0,70,14.0,chevrolet impala,usa,4354
7,8.5,8,440.0,215.0,70,14.0,plymouth fury iii,usa,4312
8,10.0,8,455.0,225.0,70,14.0,pontiac catalina,usa,4425
9,8.5,8,390.0,190.0,70,15.0,amc ambassador dpl,usa,3850

What does the end of the `DataFrame` look like? Try viewing the last few rows:

In [ ]:
# view the last 5 rows
car_data.tail()

,acceleration,cylinders,displacement,horsepower,model_year,mpg,name,origin,weight
15,15.5,6,198.0,95.0,70,22.0,plymouth duster,usa,2833
16,15.5,6,199.0,97.0,70,18.0,amc hornet,usa,2774
17,16.0,6,200.0,85.0,70,21.0,ford maverick,usa,2587
18,14.5,4,97.0,88.0,70,27.0,datsun pl510,japan,2130
19,20.5,4,97.0,46.0,70,26.0,volkswagen 1131 deluxe sedan,europe,1835

What happens when you call `head` or `tail` without putting a number between the parentheses?

In [ ]:
# try using head without a number
car_data.head()

,acceleration,cylinders,displacement,horsepower,model_year,mpg,name,origin,weight
0,12.0,8,307.0,130.0,70,18.0,chevrolet chevelle malibu,usa,3504
1,11.5,8,350.0,165.0,70,15.0,buick skylark 320,usa,3693
2,11.0,8,318.0,150.0,70,18.0,plymouth satellite,usa,3436
3,12.0,8,304.0,150.0,70,16.0,amc rebel sst,usa,3433
4,10.5,8,302.0,140.0,70,17.0,ford torino,usa,3449

In [ ]:
# try using tail without a number
car_data.tail()

,acceleration,cylinders,displacement,horsepower,model_year,mpg,name,origin,weight
15,15.5,6,198.0,95.0,70,22.0,plymouth duster,usa,2833
16,15.5,6,199.0,97.0,70,18.0,amc hornet,usa,2774
17,16.0,6,200.0,85.0,70,21.0,ford maverick,usa,2587
18,14.5,4,97.0,88.0,70,27.0,datsun pl510,japan,2130
19,20.5,4,97.0,46.0,70,26.0,volkswagen 1131 deluxe sedan,europe,1835

What do the rows of the `DataFrame` represent?

**Answer:**cars

What measurements or observations do we have about the data?

**Answers:**horsepower, model & year, mpg, name of vehicles, name of origin, weight

What types of variables are in each of the columns?

**Answers:**

- **acceleration**:Numerical
- **cylinders**:Numerical
- **displacement**:Numerical
- **horsepower**:Numerical
- **model_year**:Numerical
- **mpg**:Numerical
- **name**:categorical
- **origin**:Categorical
- **weight**:Numerical

# Practice: Reading Data with Pandas

Let's start by importing pandas. Remember to give it its special nickname!

In [15]:
import pandas as pd

We have another dataset called `iris` located in the GWC GitHub. Let's load it into a DataFrame called `iris`:

In [19]:
from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data
target = iris.target
names = iris.target_names
columns=iris.feature_names # (Hint: use this as columns)
# load the iris dataset into a DataFrame
iris = load_iris()

Explore the `DataFrame`; take a look at the beginning and end:

In [22]:
# View the first few rows
df = pd.DataFrame(X, columns=columns)
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [23]:
# View the last few rows
df.tail()
print(df.tail())

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

After taking a close look at the data, what do you think each row in the DataFrame represents?

**Answer**: Each row represents an individual flower.

How many rows are in the `DataFrame`? Use `len` to find out:

In [24]:
# number of rows
df.shape[0]

150

How many columns are in the `DataFrame`? Use `columns` and `len` to find out:

In [25]:
# number of columns
len(columns)

4

How many data points are in the `DataFrame`?

In [26]:
# calculate the number of data points
len(df) * len(df.columns)

600

# Practice with `numpy`!

**Remember:**
* Numpy provides a bunch of useful tools for performing calculations
* You access numpy functions by calling `np.function_name`

First, __import numpy__. Remember to use the nickname!

In [27]:
# load numpy
import numpy as np

Use numpy to __create a list of numbers from 0 through 99.__ We'll use a function called __`arange`.__

In [28]:
# Use np.arrange to generate an array of numbers and assign it to a variable called numbers
numbers = np.arange(100)

# print the array to see what it looks like
print(numbers)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Now use numpy's function called __`zeros`__ to __create another empty array__ of the same size:

In [29]:
# Create an empty array with np.zeros and assign it to a variable
arr = np.zeros(10)

# print it
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Now try manipulating the arrays using basic math:

In [30]:
# Add the numbers array to itself
result = numbers + numbers
print(result)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]

In [31]:
# Multiply the numbers array to itself
results = numbers * numbers
print(result)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]

Note that when you perform a math operation on an array, __it will often perform that operation on each item in that array.__ It's convenient that __we don't have to loop through all the values__ to apply the math operation to every item in the array.

__You can find information about the size of an array by using `.shape`.__ Note that `.shape` is an *attribute* of array -- a special variable that belongs to every *array object*. Try it out:

*HINT*: Because `.shape` is not a function you don't need to use parentheses.

In [32]:
# Use shape to view the size of your array
print(numbers.shape)

(100,)

`.shape` gave us just one number, because our array has only 1 dimension. Later we'll see what it looks like for arrays with more than 1 dimension.

Numpy also allows you to create 2D arrays, like with lists. We can __use the `method` called `reshape` to change an 1-dimensional `array` into a 2-dimensional `array`.__ `reshape` takes two arguments: the number of rows and the number of columns. Try turning one of your arrays into a 2D array using `reshape`.

In [34]:
# Reshape one of your arrays into a 2D array
numbers_2d = numbers.reshape(10, 10)
# print out the array
print(numbers_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

Now the `.shape` of your array should be changed, __try printing it out below:__

In [35]:
# Print the shape of your new array
print(numbers_2d.shape)

(10, 10)

Now we will try a couple of numpy's math functions!

In [36]:
# try using np.sum to add the items in a list together
total = np.sum(numbers)
print(total)

4950

In [37]:
# try squaring the value of each item in your array
squared = numbers ** 2
print(squared)

[   0    1    4    9   16   25   36   49   64   81  100  121  144  169
  196  225  256  289  324  361  400  441  484  529  576  625  676  729
  784  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681
 1764 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025
 3136 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761
 4900 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889
 7056 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409
 9604 9801]

__Try converting the `numbers` array to an array of floats__ using the method called `astype`:

In [38]:
# Convert the array into an array of floats
float_array = numbers.astype(float)
print(float_array)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]

Nice job! You just practiced:

* Using `numpy` to perform `array` operations.
* Performing math with `numpy`.


# Convert this notebook into html file


1.   Click on **File** and then **Download** select **Download as .ipynb**. This will download the notebook file (in this case, DTSC610_HW3.ipynb) to your computer.
2.   Upload the downloaded .ipynb file (in this case, DTSC610_HW3.ipynb) back to Colab by Click on the **Upload** icon
3.   And run the cell below.
4.   Then you can click on the **Refresh** icon (next to **Upload** icon) to obtain the generated html file (in this case, DTSC610_HW3.html).
5.   Download the generated html file by click on the three vetical dots next ot the file name.

More detailed instruction can be found on [Stackoverflow](https://stackoverflow.com/questions/53460051/convert-ipynb-notebook-to-html-in-google-colab).

In [ ]:
%%shell
jupyter nbconvert --to html DTSC610_HW3.ipynb